[package]
edition = "2018"
name = "findfire"
version = "0.1.0"

[dependencies]
chrono = "^0.4.19"
gdal = "^0.9.0"
gdal-sys = "^0.5.0"
rusqlite = {version="^0.25.3", features=["chrono"]}
walkdir = "^2.3.2"
