[package]
edition = "2018"
name = "satfire"
version = "0.1.0"

[dependencies]
chrono = "^0.4.19"
crossbeam-channel = "^0.5.0"
gdal = "^0.9.0"
gdal-sys = "^0.5.0"
log = {version = "^0.4.14", features=["max_level_debug", "release_max_level_debug", "std"]}
rusqlite = {version="^0.25.3", features=["chrono"]}
simple_logger = {version = "^1.13.0"}
walkdir = "^2.3.2"
