[package]
edition = "2018"
name = "satfire"
version = "0.2.0"

[dependencies]
approx = "^0.4.0"
bincode = "^1.3.3"
chrono = "^0.4.19"
crossbeam-channel = "^0.5.0"
gdal = "^0.9.0"
geo = {version = "^0.18.0", features = ["use-serde"]}
itertools = "0.10.1"
kd-tree = "^0.4.1"
kml = {version = "^0.3.1", features=["geo-types"]}
log = {version = "^0.4.14", features=["max_level_debug", "release_max_level_debug", "std"]}
rusqlite = {version="^0.25.3", features=["chrono"]}
serde = "^1.0.117"
simple_logger = {version = "^1.13.0"}
strum = { version = "0.21", features = ["derive"] }
typenum = "^1.14.0"
walkdir = "^2.3.2"
