[package]
name = "satfire"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "^0.4.19"
netcdf = {version="^0.7.0", features=["memory"]}
rusqlite = {version="^0.26.0", features=["blob", "chrono"]}
walkdir = "^2"
zip = "0.5"
